apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-frontend
  labels: 
    app: myapp-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp-frontend
  template:
    metadata:
      labels:
        app: myapp-frontend
    spec:
      containers:
      - name: myapp-frontend
        image: darius001/frontend:latest
        ports: 
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: myapp-frontend
spec:
  selector:
    app: myapp-frontend
  type: LoadBalancer
  ports:
  - port: 3000
    targetPort: 80
    protocol: TCP

